# Generated by Django 3.1.6 on 2021-05-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20210517_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles_and_users_intermediate_table',
            options={'verbose_name': 'Лайк статьи', 'verbose_name_plural': 'Лайки статей'},
        ),
        migrations.AlterModelOptions(
            name='intermediate_table_of_cometaries_and_users',
            options={'verbose_name': 'Лайк комента', 'verbose_name_plural': 'Лайки коментариев'},
        ),
    ]
